name: Build & Push to ACR

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          TOKEN=$(az acr login --name "$ACR_NAME" --expose-token --query accessToken -o tsv)
          echo "$TOKEN" | docker login "$ACR_LOGIN_SERVER" \
            --username 00000000-0000-0000-0000-000000000000 \
            --password-stdin

      - name: Build image
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          docker build -t "$ACR_LOGIN_SERVER/node-aks-app:1.0.0" .

      - name: Push image
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          docker push "$ACR_LOGIN_SERVER/node-aks-app:1.0.0"

      - name: Output image ref
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: echo "✅ Image pushed: $ACR_LOGIN_SERVER/node-aks-app:1.0.0"
