name: Build & Push to ACR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: TOKEN=$(az acr login --name aksdemoacr4895 --expose-token --query accessToken -o tsv) && echo "$TOKEN" | docker login aksdemoacr4895.azurecr.io --username 00000000-0000-0000-0000-000000000000 --password-stdin

      - name: Build image
        run: docker build -t aksdemoacr4895.azurecr.io/node-aks-app:1.0.1 .

      - name: Push image
        run: docker push aksdemoacr4895.azurecr.io/node-aks-app:1.0.1

      - name: Output image ref
        run: echo "Image"
