name: Build & Push to ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC login
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ✅ Login to Azure using OIDC + AZURE_CREDENTIALS JSON
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Login to ACR using Azure CLI (no username/password required)
      - name: ACR Login (AAD)
        run: |
          az acr login -n aksdemoacr4895

      # ✅ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE="aksdemoacr4895.azurecr.io/node-aks-app:1.0.6"
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .

      # ✅ Push image
      - name: Push Docker image
        run: |
          IMAGE="aksdemoacr4895.azurecr.io/node-aks-app:1.0.6"
          echo "Pushing image: $IMAGE"
          docker push $IMAGE

      # ✅ Output image tag
      - name: Show pushed image
        run: echo "✅ Image pushed: aksdemoacr4895.azurecr.io/node-aks-app:1.0.6"
